# Schema for configuration files of the Password Policy Length submodule.

password_policy_length.constraint.plugin.password_length:
  type: password_policy_length.constraint.plugin
  mapping:
    character_length:
      type: integer