password_policy.password_constraint.*:
  type: config_entity
  label: 'Password Constraint'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    plugin_id:
      type: string
    settings:
      type: password_policy.constraint_settings.[%parent.plugin]

password_policy.constraint_settings.settings.*:
  type: password_constraint_settings
