# Schema for configuration files of the Password Policy module.

password_policy.password_policy.*:
  type: mapping
  label: 'Password policy'
  mapping:
    pid:
      type: string
      label: 'Policy identifier'
    policy_title:
      type: label
      label: 'Name'
      translatable: true
    password_reset:
      type: integer
      label: 'Password reset'
    policy_constraints:
      type: sequence
      label: 'Constraints'
      sequence:
        type: mapping
        mapping:
          key:
            type: string
            label: 'Plugin'
          constraints:
            type: sequence
            sequence:
              type: mapping
              mapping:
                constraint_id:
                  type: integer
                  label: 'Constraint ID'

