# Schema for configuration files of the Password Policy module.

password_policy.password_policy.*:
  type: mapping
  label: 'Password policy'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
      translatable: true
    password_reset:
      type: integer
      label: 'Password reset'
    policy_constraints:
      type: sequence
      label: 'Constraints'
      sequence:
        type: password_policy.constraint.plugin.[id]
        label: 'Constraint'
    roles:
      type: sequence
      label: 'Roles'
      sequence:
        type: string
        label: 'Role'

password_policy.constraint.plugin:
  type: mapping
  label: 'Constraint settings'
  mapping:
    id:
      type: string
      label: 'ID'

password_policy.constraint.plugin.password_length:
  type: password_policy.constraint.plugin
  mapping:
    character_length:
      type: integer